"""add_escalation_brief_to_conversation

Revision ID: 4cfb7aa7bff1
Revises: fc2cd260291c
Create Date: 2026-04-02 15:27:57.870544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cfb7aa7bff1'
down_revision: Union[str, Sequence[str], None] = 'fc2cd260291c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('escalation_brief', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'escalation_brief')
    # ### end Alembic commands ###
