"""Add missing pipeline columns

Revision ID: b71772679c31
Revises: 
Create Date: 2026-03-30 10:41:53.174497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b71772679c31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('pipeline_stage_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_contacts_uuid'), 'contacts', ['uuid'], unique=True)
    op.create_foreign_key(None, 'contacts', 'pipeline_stages', ['pipeline_stage_id'], ['id'])
    op.create_index(op.f('ix_conversations_uuid'), 'conversations', ['uuid'], unique=True)
    op.drop_constraint(op.f('conversations_contact_id_fkey'), 'conversations', type_='foreignkey')
    # Use explicit name for foreign key if possible, but None is usually handled by Alembic
    op.create_foreign_key('conversations_contact_id_fkey', 'conversations', 'contacts', ['contact_id'], ['id'])
    op.create_index(op.f('ix_form_submissions_uuid'), 'form_submissions', ['uuid'], unique=True)
    op.create_index(op.f('ix_forms_uuid'), 'forms', ['uuid'], unique=True)
    op.create_index(op.f('ix_knowledge_base_intent_type'), 'knowledge_base', ['intent_type'], unique=False)
    op.create_index(op.f('ix_knowledge_base_priority'), 'knowledge_base', ['priority'], unique=False)
    # The priority column already exists, let's just make sure we don't conflict
    op.create_index(op.f('ix_knowledge_base_role_type'), 'knowledge_base', ['role_type'], unique=False)
    op.create_index(op.f('ix_knowledge_base_uuid'), 'knowledge_base', ['uuid'], unique=True)
    op.create_index(op.f('ix_messages_conversation_uuid'), 'messages', ['conversation_uuid'], unique=False)
    op.create_index(op.f('ix_messages_uuid'), 'messages', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_uuid'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_uuid'), table_name='messages')
    op.drop_index(op.f('ix_knowledge_base_uuid'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_role_type'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_priority'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_intent_type'), table_name='knowledge_base')
    op.drop_index(op.f('ix_forms_uuid'), table_name='forms')
    op.drop_index(op.f('ix_form_submissions_uuid'), table_name='form_submissions')
    op.drop_constraint('conversations_contact_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_contact_id_fkey'), 'conversations', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_uuid'), table_name='conversations')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_uuid'), table_name='contacts')
    op.drop_column('contacts', 'pipeline_stage_id')
    # ### end Alembic commands ###
