-- AI Agent Knowledge Base expansion
-- Suggested target table columns:
-- id, question, answer, category, intent_type, role_type, priority, keywords, tags, status, source

INSERT INTO knowledge_base
(id, question, answer, category, intent_type, role_type, priority, keywords, tags, status, source)
VALUES
(
1001,
'What happens when a new lead sends a message after business hours?',
'The agent should reply immediately with a professional acknowledgment, answer basic questions if possible, collect essential details, and offer the next available consultation slot or booking link. If the request sounds urgent or high-value, it should flag the conversation for human review the next business day.',
'client_communication',
'inbound_response',
'lead',
10,
'["after hours", "response time", "new lead", "business hours"]'::jsonb,
'["communication", "automation", "sla"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1002,
'Can the AI answer common client questions automatically?',
'Yes. The agent should handle repetitive questions about services, process, timelines, pricing ranges, consultation steps, and next actions. For anything unclear, high-risk, or highly customized, it should move the conversation to a human instead of guessing.',
'client_communication',
'faq_response',
'lead',
10,
'["faq", "common questions", "services", "pricing", "timeline"]'::jsonb,
'["communication", "faq"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1003,
'When should the AI escalate a conversation to a human?',
'The AI should escalate when a lead requests a custom quote, asks legal or contract-related questions, shows frustration, asks for exceptions, mentions a large budget or urgent timeline, or when the message is ambiguous enough that a wrong reply could hurt trust.',
'escalation',
'escalation_rule',
'lead',
10,
'["escalate", "human handoff", "urgent", "custom quote", "complaint"]'::jsonb,
'["handoff", "risk"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1004,
'How should the AI handle angry or frustrated messages?',
'The agent should acknowledge the concern, avoid sounding defensive, offer a simple next step, and notify a human owner immediately. In sensitive situations, speed matters more than automation, so the goal is de-escalation and a fast human follow-up.',
'client_communication',
'sentiment_response',
'client',
9,
'["angry", "frustrated", "complaint", "upset"]'::jsonb,
'["communication", "support"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1005,
'Can the AI confirm meetings and send reminders?',
'Yes. Once a booking is created, the system should confirm the appointment, restate the date and time, clarify what will be discussed, and send reminders before the call to reduce no-shows.',
'booking',
'booking_confirmation',
'lead',
9,
'["confirm meeting", "reminders", "appointment", "no show"]'::jsonb,
'["booking", "automation"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1006,
'What should the AI say when it does not know the answer?',
'It should avoid making assumptions. A safe reply is to acknowledge the question, state that a specialist will confirm the best answer, and offer the next step such as a follow-up email or consultation booking.',
'client_communication',
'fallback_response',
'lead',
10,
'["don''t know", "unknown answer", "fallback"]'::jsonb,
'["guardrails", "communication"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1007,
'How quickly should the AI respond to new inquiries?',
'For lead capture, the target should be immediate acknowledgment within seconds and a useful follow-up in the same interaction. Fast first response improves conversion, even if a human follows later for the detailed discussion.',
'client_communication',
'sla_question',
'lead',
8,
'["response time", "sla", "first response"]'::jsonb,
'["communication", "conversion"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1008,
'Can the AI collect missing information before a human steps in?',
'Yes. The agent should gather essentials like service needed, project type, timeline, budget range, business type, and preferred contact method so the human team receives a qualified conversation instead of a cold lead.',
'lead_qualification',
'qualification_intake',
'lead',
10,
'["collect info", "qualification", "intake", "missing information"]'::jsonb,
'["qualification", "intake"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1009,
'How should the AI route high-value leads?',
'High-value leads should be tagged based on budget range, urgency, business fit, and buying intent. They should be moved to a priority pipeline stage, assigned to a human quickly, and given faster follow-up windows.',
'lead_qualification',
'lead_scoring',
'lead',
10,
'["high value lead", "priority", "hot lead", "scoring"]'::jsonb,
'["qualification", "scoring"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1010,
'What channels should the AI support first?',
'Start with the channels where your inbound and follow-up volume is highest, usually website chat, email, SMS, and calendar booking. Add more channels after the core flows are stable and measurable.',
'system_strategy',
'channel_strategy',
'internal',
7,
'["channels", "email", "sms", "website chat"]'::jsonb,
'["strategy", "operations"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1011,
'What questions should the AI ask a new lead first?',
'Start with the minimum needed to qualify without creating friction: what they need help with, whether they need a website, app, automation, or AI solution, target timeline, rough budget, and whether they are the decision-maker.',
'lead_qualification',
'qualification_question',
'lead',
10,
'["qualifying questions", "new lead", "first questions"]'::jsonb,
'["qualification"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1012,
'How can the AI tell if a lead is qualified?',
'A qualified lead usually has a clear problem, a defined business need, a realistic timeline, some budget awareness, and access to decision-making. If those signals are missing, the system should keep nurturing instead of forcing a sales call.',
'lead_qualification',
'qualification_logic',
'lead',
10,
'["qualified lead", "serious lead", "decision maker", "budget"]'::jsonb,
'["qualification", "logic"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1013,
'What budget question should the AI ask without sounding pushy?',
'A good approach is to ask whether they already have a budget range in mind or if they want guidance based on scope. This keeps the tone consultative while still helping the team separate serious projects from early exploration.',
'lead_qualification',
'budget_question',
'lead',
9,
'["budget range", "pricing", "pushy", "scope"]'::jsonb,
'["qualification", "pricing"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1014,
'How should the AI qualify timeline?',
'The agent should ask whether the project is urgent, planned for a specific launch, or still in early exploration. This helps separate active buyers from leads who need education first.',
'lead_qualification',
'timeline_question',
'lead',
8,
'["timeline", "urgency", "launch date"]'::jsonb,
'["qualification", "timeline"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1015,
'What should the AI do if a lead does not know the scope yet?',
'It should switch from hard qualification to guided discovery by asking about the business goal, current pain points, audience, and must-have outcomes. That allows the team to shape scope later without losing the opportunity.',
'lead_qualification',
'scope_unclear',
'lead',
9,
'["don''t know scope", "unclear scope", "discovery"]'::jsonb,
'["qualification", "discovery"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1016,
'How should the AI identify decision-makers?',
'It should politely ask who will be involved in approving the project and whether anyone else should join the consultation. This reduces delays later in the sales cycle.',
'lead_qualification',
'authority_check',
'lead',
9,
'["decision maker", "approval", "stakeholders"]'::jsonb,
'["qualification", "authority"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1017,
'What signals suggest the lead is not ready yet?',
'Signals include very vague needs, no urgency, no budget thinking at all, avoidance of next steps, or requests for fully custom advice before any discovery call. These leads should go into nurture rather than immediate sales handling.',
'lead_qualification',
'not_ready',
'lead',
8,
'["not ready", "early stage", "vague lead"]'::jsonb,
'["qualification", "nurture"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1018,
'Should the AI send an intake form before booking?',
'Yes, for higher-value or more complex projects. For simple inquiries, booking can happen first. For complex work, a short intake form improves call quality and helps the team prepare.',
'lead_qualification',
'intake_form',
'lead',
8,
'["intake form", "before booking", "questionnaire"]'::jsonb,
'["qualification", "booking"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1019,
'How can the AI separate website leads from AI automation leads?',
'It should classify the inquiry based on the main pain point: brand presence and conversion usually point to website work, product workflows and data handling point to software, and repetitive communication or qualification needs point to automation or AI agents.',
'lead_qualification',
'service_classification',
'lead',
9,
'["website or app", "automation", "ai agent", "classify lead"]'::jsonb,
'["qualification", "routing"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1020,
'How should the AI handle price shoppers?',
'It should give transparent pricing ranges, explain what affects cost, and move the conversation toward scope and outcomes. If the lead only wants the cheapest option, the system should keep the interaction helpful without overcommitting team time.',
'pricing',
'price_shopper',
'lead',
8,
'["cheap", "lowest price", "price shopper"]'::jsonb,
'["pricing", "qualification"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1021,
'When should the AI offer a booking link?',
'Offer the booking link once the lead has shown interest and shared enough context to make the meeting useful. Too early feels transactional, too late slows conversion.',
'booking',
'booking_trigger',
'lead',
9,
'["booking link", "when to send", "consultation"]'::jsonb,
'["booking", "conversion"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1022,
'What should happen after a consultation is booked?',
'The CRM should create or update the contact, store qualification notes, assign the opportunity stage, send confirmation and reminders, and prepare the team with the lead summary before the meeting.',
'crm_workflow',
'post_booking_workflow',
'internal',
10,
'["after booking", "crm update", "reminders", "lead summary"]'::jsonb,
'["crm", "workflow"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1023,
'How should the AI reduce no-shows?',
'Use clear confirmations, one-day and one-hour reminders, a short summary of what the call will cover, and easy rescheduling options. People attend more when the meeting feels relevant and easy to manage.',
'booking',
'no_show_reduction',
'lead',
8,
'["no show", "reminders", "reschedule"]'::jsonb,
'["booking", "optimization"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1024,
'What should the AI ask before scheduling a consultation?',
'It should confirm the service needed, the business goal, urgency, and whether the lead is the right contact. That keeps the calendar from filling with low-fit calls.',
'booking',
'pre_booking_questions',
'lead',
8,
'["before scheduling", "consultation questions"]'::jsonb,
'["booking", "qualification"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1025,
'Can the AI reschedule missed appointments automatically?',
'Yes. If a lead misses a meeting, the system should send a polite follow-up, offer a reschedule link, and keep the conversation warm instead of closing it too early.',
'booking',
'reschedule_flow',
'lead',
7,
'["missed appointment", "reschedule", "no show"]'::jsonb,
'["booking", "followup"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1026,
'How should the AI handle outbound outreach to contractors or real estate partners?',
'The outreach should be short, relevant, and based on the partner''s business type. The message should focus on a clear value proposition, one reason the outreach is relevant to them, and one simple next step such as a call or reply.',
'outreach',
'outbound_message',
'partner',
10,
'["contractor outreach", "real estate agent", "partner outreach"]'::jsonb,
'["outreach", "partnership"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1027,
'What makes a good first outreach message?',
'A good first message is personalized, industry-relevant, and specific about the problem you solve. It should avoid sounding mass-sent and should end with a low-friction call to action.',
'outreach',
'message_quality',
'partner',
9,
'["first outreach message", "personalization", "CTA"]'::jsonb,
'["outreach"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1028,
'How many follow-ups should the system send automatically?',
'A practical default is three to five follow-ups spaced over days or weeks, with each message adding a different angle such as value, case relevance, or timing. More than that can feel spammy unless engagement signals are positive.',
'outreach',
'followup_cadence',
'partner',
8,
'["follow up sequence", "outreach cadence", "spam"]'::jsonb,
'["outreach", "cadence"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1029,
'What should the AI track during outreach?',
'Track contact role, company, industry, message history, reply status, interest level, objections, and whether a partnership call was booked. Without this, outreach becomes hard to optimize.',
'outreach',
'outreach_tracking',
'internal',
8,
'["track outreach", "replies", "objections", "call booked"]'::jsonb,
'["outreach", "crm"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1030,
'How should the AI qualify a potential referral partner?',
'A strong partner fit usually has audience overlap, steady deal flow, credibility in the market, and a clear reason to refer or collaborate. The system should capture those signals before pushing for a call.',
'partnership',
'partner_qualification',
'partner',
9,
'["referral partner", "partnership fit", "collaborate"]'::jsonb,
'["partnership", "qualification"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1031,
'What should the AI do when a partner shows interest?',
'It should move the contact into a partner pipeline, capture notes on opportunity type and value, send a follow-up or booking link, and notify the right team member for relationship handling.',
'partnership',
'partner_interest',
'partner',
8,
'["partner interested", "next step", "pipeline"]'::jsonb,
'["partnership", "workflow"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1032,
'What should the AI say in a referral workflow?',
'It should clearly explain how referrals are handled, what kind of clients are a good fit, and what the next step is. Clarity matters because referral programs fail when expectations stay vague.',
'partnership',
'referral_explainer',
'partner',
7,
'["referral workflow", "how referrals work"]'::jsonb,
'["partnership", "process"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1033,
'How should the AI avoid spammy outreach behavior?',
'It should personalize at least one line, limit message frequency, stop sequences on negative signals, and avoid repeating the same wording across follow-ups. The goal is relationship-building, not volume alone.',
'outreach',
'anti_spam',
'internal',
8,
'["spam", "repetitive outreach", "stop sequence"]'::jsonb,
'["outreach", "quality"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1034,
'What should happen in the CRM when a new lead is captured?',
'The system should create or update the contact, assign source and channel, store the conversation summary, set an initial pipeline stage, and trigger the next follow-up action automatically.',
'crm_workflow',
'new_lead_workflow',
'internal',
10,
'["new lead", "crm update", "pipeline stage", "source"]'::jsonb,
'["crm", "workflow"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1035,
'What fields are most important to store for qualified leads?',
'Store service interest, business type, budget range, timeline, decision-maker status, pain points, source channel, last interaction date, next step, and assigned owner. These fields improve follow-up quality and reporting.',
'crm_workflow',
'crm_fields',
'internal',
10,
'["crm fields", "budget", "timeline", "owner", "source"]'::jsonb,
'["crm", "data"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1036,
'How should the AI keep the pipeline organized?',
'It should update lead stages based on conversation signals, create reminders when a next step is agreed, and flag stalled deals that have had no reply within the expected window.',
'crm_workflow',
'pipeline_hygiene',
'internal',
9,
'["pipeline organized", "stalled deals", "follow up"]'::jsonb,
'["crm", "pipeline"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1037,
'What triggers should create a follow-up task automatically?',
'A follow-up task should be created after a consultation, after a positive reply without booking, after a missed appointment, after an unanswered proposal, or after a lead asks for more information.',
'crm_workflow',
'followup_trigger',
'internal',
9,
'["follow up task", "automate follow up", "trigger"]'::jsonb,
'["crm", "automation"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1038,
'How should the AI update CRM notes?',
'It should summarize the conversation into business-relevant notes: what the lead wants, how urgent it is, any budget clues, objections, next step, and sentiment. Raw transcripts alone are not enough for sales teams.',
'crm_workflow',
'crm_notes',
'internal',
8,
'["conversation summary", "crm notes", "objections"]'::jsonb,
'["crm", "notes"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1039,
'What should happen when a lead stops replying?',
'The system should move the lead into a follow-up or nurture status, send a timed re-engagement message if appropriate, and stop active selling after repeated non-response unless the lead reopens the conversation.',
'crm_workflow',
'no_response_flow',
'lead',
8,
'["ghosted lead", "stopped replying", "re-engagement"]'::jsonb,
'["crm", "nurture"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1040,
'Can the AI use Google Sheets as a lightweight tracking layer?',
'Yes. Sheets can work for simple tracking, reporting, or backup workflows, but the primary source of truth should stay in the CRM to avoid fragmented lead history.',
'crm_workflow',
'sheets_usage',
'internal',
6,
'["google sheets", "tracking", "crm source of truth"]'::jsonb,
'["crm", "ops"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1041,
'What should be the source of truth for lead stage?',
'The CRM should be the source of truth for lead stages, owner assignment, and next actions. Other tools can mirror data, but decision-making should not depend on scattered records.',
'crm_workflow',
'source_of_truth',
'internal',
8,
'["source of truth", "crm", "pipeline"]'::jsonb,
'["crm", "governance"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1042,
'How should the AI decide between replying immediately and escalating?',
'If the message matches a known FAQ or clear workflow, reply immediately. If it involves custom scope, risk, urgency, high-value opportunity, or negative sentiment, escalate or reply with a controlled handoff.',
'smart_decisioning',
'respond_vs_escalate',
'internal',
10,
'["reply or escalate", "decision rule", "sentiment"]'::jsonb,
'["decisioning", "handoff"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1043,
'What tone should the AI maintain in conversations?',
'The tone should be professional, clear, helpful, and confident without sounding robotic or overly salesy. The goal is to build trust and move the conversation forward naturally.',
'smart_decisioning',
'tone_guideline',
'internal',
9,
'["tone", "professional", "salesy", "natural"]'::jsonb,
'["tone", "brand"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1044,
'How should the AI avoid sounding robotic?',
'It should use concise human language, acknowledge the specific question, avoid repeating templates too often, and adapt the reply to the lead''s context instead of forcing generic copy.',
'smart_decisioning',
'human_tone',
'internal',
8,
'["robotic", "human sounding", "natural reply"]'::jsonb,
'["tone", "quality"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1045,
'Can the AI learn from conversations over time?',
'Yes, but it should learn through controlled review loops, approved prompt or KB updates, and analysis of successful conversations. It should not change business-critical behavior automatically without oversight.',
'smart_decisioning',
'learning_loop',
'internal',
8,
'["learn over time", "feedback loop", "improve"]'::jsonb,
'["decisioning", "learning"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1046,
'What should the AI optimize for first?',
'Initially it should optimize for speed to first response, qualification completion rate, consultation bookings, and clean CRM updates. Those metrics create the fastest business impact.',
'system_strategy',
'optimization_priority',
'internal',
9,
'["kpi", "optimize first", "booking rate", "response time"]'::jsonb,
'["strategy", "kpi"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1047,
'How should the system identify a hot lead?',
'A hot lead usually has a clear need, urgency, buying authority, budget readiness, and positive engagement with next steps. Those leads should receive faster human attention and tighter follow-up windows.',
'lead_qualification',
'hot_lead',
'internal',
9,
'["hot lead", "urgency", "authority", "budget"]'::jsonb,
'["qualification", "scoring"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1048,
'How should the system handle cold or low-fit leads?',
'It should still respond politely, provide helpful direction where possible, and move them into nurture or low-priority handling rather than spending premium sales time too early.',
'lead_qualification',
'cold_lead',
'internal',
7,
'["cold lead", "low fit", "nurture"]'::jsonb,
'["qualification", "nurture"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1049,
'How should the AI handle custom project requests?',
'It should gather the business goal, likely scope, timeline, and budget clues, then offer a consultation or human follow-up. Custom work should not be quoted too precisely without discovery.',
'pricing',
'custom_request',
'lead',
9,
'["custom project", "quote", "discovery"]'::jsonb,
'["pricing", "scoping"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1050,
'What should the AI do when multiple services may fit the lead?',
'It should recommend the most likely starting path based on the lead''s goal and explain why. If there is uncertainty, it should position the consultation as the best way to refine the solution.',
'smart_decisioning',
'multi_service_routing',
'lead',
8,
'["multiple services", "best fit", "recommend"]'::jsonb,
'["routing", "sales"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1051,
'What should the AI say when the lead says the price is too high?',
'It should acknowledge the concern, reconnect the quote to scope and outcomes, and offer a phased approach if appropriate. The goal is to keep the conversation moving without discounting by default.',
'pricing',
'price_objection',
'lead',
9,
'["too expensive", "high price", "budget issue"]'::jsonb,
'["pricing", "objection"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1052,
'What should the AI say when the lead wants to think about it?',
'It should respect the pause, ask if any specific concerns are blocking a decision, and agree on a clear follow-up point. Open loops convert better than vague goodbyes.',
'sales_objection',
'delay_objection',
'lead',
8,
'["think about it", "follow up later", "unsure"]'::jsonb,
'["objection", "followup"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1053,
'How should the AI respond when a lead compares you to competitors?',
'It should stay calm, focus on fit, process quality, speed, reliability, and outcomes, and avoid negative language about competitors. Comparison moments are best handled with clarity, not defensiveness.',
'sales_objection',
'competitor_comparison',
'lead',
7,
'["competitor", "compare agencies", "alternative"]'::jsonb,
'["objection", "positioning"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1054,
'What should the AI say when the lead wants an estimate before a call?',
'It can share a realistic range based on similar scopes, explain what drives the cost, and note that the detailed estimate comes after understanding the requirements properly.',
'pricing',
'estimate_before_call',
'lead',
8,
'["estimate before call", "rough quote", "pricing range"]'::jsonb,
'["pricing", "conversion"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1055,
'How should the AI move a lead from interest to booked consultation?',
'It should summarize the need, confirm that a short call would help clarify scope or next steps, and then provide a simple booking option. Momentum matters most right after interest is expressed.',
'booking',
'interest_to_booking',
'lead',
9,
'["book consultation", "move to call", "next step"]'::jsonb,
'["booking", "conversion"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1056,
'What should the AI do after sending a proposal?',
'It should log the proposal stage, set a timed follow-up, capture any objections or open questions, and remind the team if the lead goes quiet beyond the expected decision window.',
'crm_workflow',
'post_proposal',
'internal',
8,
'["after proposal", "follow up", "decision window"]'::jsonb,
'["crm", "sales"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1057,
'How should the AI handle referral-source leads differently?',
'Referral leads should be acknowledged quickly, tagged by source, and treated with context about the referring relationship. Referral trust is an asset, so the follow-up should feel more personal.',
'lead_qualification',
'referral_lead',
'lead',
8,
'["referral lead", "referred by", "source"]'::jsonb,
'["qualification", "referral"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1058,
'What should the AI ask before preparing a proposal?',
'It should confirm the business objective, required deliverables, timeline, budget expectations, decision-makers, and any must-have integrations or constraints. Proposals are better when those basics are clear.',
'lead_qualification',
'proposal_readiness',
'lead',
9,
'["before proposal", "scope", "budget", "integrations"]'::jsonb,
'["qualification", "proposal"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1059,
'What metrics should we track to judge whether the AI agent is working?',
'Track first-response speed, qualification completion rate, booking rate, show-up rate, positive reply rate, pipeline progression, and human takeover rate. These reveal both efficiency and revenue impact.',
'reporting',
'performance_metrics',
'internal',
10,
'["metrics", "booking rate", "reply rate", "human takeover"]'::jsonb,
'["analytics", "kpi"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1060,
'How do we know if the outreach workflow is effective?',
'Look at open or reply signals where available, positive reply rate, meetings booked, partner conversion rate, and time from first contact to response. Activity volume alone is not enough.',
'reporting',
'outreach_metrics',
'internal',
8,
'["outreach metrics", "positive reply", "meetings booked"]'::jsonb,
'["analytics", "outreach"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1061,
'What metric shows lead quality best?',
'A strong proxy is the percentage of captured leads that progress to consultation and then to proposal or serious sales discussion. High lead volume means little if conversion stays weak.',
'reporting',
'lead_quality_metric',
'internal',
8,
'["lead quality", "consultation rate", "conversion"]'::jsonb,
'["analytics", "qualification"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
),
(
1062,
'How should we measure AI handoff quality?',
'Measure how often escalated conversations have enough context for a human to act immediately, and whether the human needs to repeat qualification steps. Good handoff reduces friction, not just workload.',
'reporting',
'handoff_quality',
'internal',
7,
'["handoff quality", "escalation context", "friction"]'::jsonb,
'["analytics", "handoff"]'::jsonb,
'draft_ready',
'generated_for_ai_agent_kb'
)
ON CONFLICT (id) DO UPDATE SET
question = EXCLUDED.question,
answer = EXCLUDED.answer,
category = EXCLUDED.category,
intent_type = EXCLUDED.intent_type,
role_type = EXCLUDED.role_type,
priority = EXCLUDED.priority,
keywords = EXCLUDED.keywords,
tags = EXCLUDED.tags,
status = EXCLUDED.status,
source = EXCLUDED.source;
